In [1]:
from scheduler import Timetable

### Relaxed problem with two removed lectures

In [2]:
# name
lecture_list = [
    'Lecture 1',
    'Lecture 2',
    'Lecture 3',
    'Lecture 4',
    'Lecture 5',
    'Lecture 6',
    'Lecture 7',
    'Lecture 8',
    'Lecture 9',
    'Lecture 10',
    'Lecture 11',
    'Lecture 12',
    'Lecture 13',
    'Lecture 14',
    'Lecture 15',
    'Lecture 16',
    'Lecture 17',
#     'Lecture 18',
#     'Lecture 19',
    'Lecture 20',
]
# name lectures[] days[] times
instructor_list = [
    ['1', ['Lecture 1',
            'Lecture 2',
            'Lecture 3',
            'Lecture 4',
            'Lecture 5',], ['Tue', 'Wed', 'Thu'], []],
    ['2', ['Lecture 1',
            'Lecture 2',
            'Lecture 3',
            'Lecture 4',
            'Lecture 5',
            'Lecture 11',
            'Lecture 12',
            'Lecture 13',
            'Lecture 14',
            'Lecture 15',], ['Mon', 'Tue', 'Wed'], []],
    ['3', ['Lecture 6',
            'Lecture 7',
            'Lecture 8',
            'Lecture 9',
            'Lecture 10',
            'Lecture 16',
            'Lecture 17',
            'Lecture 18',
            'Lecture 19',
            'Lecture 20',], ['Thu', 'Fri'], []],
    ['4', ['Lecture 6',
            'Lecture 7',
            'Lecture 8',
            'Lecture 9',
            'Lecture 10',], [], ['10-12', '12-14']],
    ['5', ['Lecture 11',
            'Lecture 12',
            'Lecture 13',
            'Lecture 14',
            'Lecture 15',
            'Lecture 16',
            'Lecture 17',
            'Lecture 18',
            'Lecture 19',
            'Lecture 20',], [], ['8-10', '10-12']],
]
# number lectures days times
room_list = [
    [1, ['Lecture 1',
        'Lecture 2',
        'Lecture 3',
        'Lecture 4',
        'Lecture 5',
        'Lecture 6',
        'Lecture 7',
        'Lecture 8',
        'Lecture 9',
        'Lecture 10',
        'Lecture 11',
        'Lecture 12',
        'Lecture 13',
        'Lecture 14',
        'Lecture 15',
        'Lecture 16',
        'Lecture 17',
        'Lecture 18',
        'Lecture 19',
        'Lecture 20',], ['Mon'], []],
    [2, ['Lecture 1',
        'Lecture 2',
        'Lecture 3',
        'Lecture 4',
        'Lecture 5',
        'Lecture 6',
        'Lecture 7',
        'Lecture 8',
        'Lecture 9',
        'Lecture 10',], ['Mon', 'Tue', 'Wed', 'Thu'], []],
    [3, ['Lecture 11',
        'Lecture 12',
        'Lecture 13',
        'Lecture 14',
        'Lecture 15',
        'Lecture 16',
        'Lecture 17',
        'Lecture 18',
        'Lecture 19',
        'Lecture 20',], ['Tue', 'Wed', 'Thu', 'Fri'], []],
    [4, ['Lecture 1',
        'Lecture 2',
        'Lecture 3',
        'Lecture 4',
        'Lecture 5',
        'Lecture 6',
        'Lecture 7',
        'Lecture 8',
        'Lecture 9',
        'Lecture 10',], [], ['8-10']],
    [5, ['Lecture 11',
        'Lecture 12',
        'Lecture 13',
        'Lecture 14',
        'Lecture 15',
        'Lecture 16',
        'Lecture 17',
        'Lecture 18',
        'Lecture 19',
        'Lecture 20',], [], ['12-14']],
]
# day start-end
timeslot_list = [
    'Mon 8-10',
    'Mon 10-12',
    'Mon 12-14',
    'Tue 8-10',
    'Tue 10-12',
    'Tue 12-14',
    'Wed 8-10',
    'Wed 10-12',
    'Wed 12-14',
    'Thu 8-10',
    'Thu 10-12',
    'Thu 12-14',
    'Fri 8-10',
    'Fri 10-12',
    'Fri 12-14',
]

In [3]:
timetable = Timetable(lecture_list, instructor_list, room_list, timeslot_list,
                      max_lectures_per_instructor=5)

In [4]:
%%time
timetable.find_schedule()
print(timetable)

+------------+-----------+------------+------+
|  Lecture   |    Time   | Instructor | Room |
+------------+-----------+------------+------+
| Lecture 15 | Fri 10-12 |     5      | No.3 |
| Lecture 20 | Fri 12-14 |     3      | No.3 |
| Lecture 8  | Mon 10-12 |     4      | No.2 |
| Lecture 5  | Mon 10-12 |     2      | No.1 |
| Lecture 2  | Mon 12-14 |     2      | No.1 |
| Lecture 7  | Mon 12-14 |     4      | No.2 |
| Lecture 16 | Thu 10-12 |     5      | No.3 |
| Lecture 10 | Thu 10-12 |     4      | No.2 |
| Lecture 6  | Thu 12-14 |     4      | No.2 |
| Lecture 17 | Thu 12-14 |     3      | No.5 |
| Lecture 1  | Tue 10-12 |     1      | No.2 |
| Lecture 13 | Tue 10-12 |     5      | No.3 |
| Lecture 3  | Tue 12-14 |     1      | No.2 |
| Lecture 14 | Tue 12-14 |     2      | No.5 |
| Lecture 4  | Wed 10-12 |     1      | No.2 |
| Lecture 11 | Wed 10-12 |     5      | No.3 |
| Lecture 12 | Wed 12-14 |     2      | No.5 |
| Lecture 9  | Wed 12-14 |     4      | No.2 |
+------------+-----------+------------+------+
CPU times: user 7.29 s, sys: 12 ms, total: 7.3 s
Wall time: 7.31 s

### Relaxed problem with three removed lectures

In [5]:
# name
lecture_list = [
    'Lecture 1',
    'Lecture 2',
    'Lecture 3',
    'Lecture 4',
    'Lecture 5',
    'Lecture 6',
    'Lecture 7',
    'Lecture 8',
    'Lecture 9',
    'Lecture 10',
    'Lecture 11',
    'Lecture 12',
    'Lecture 13',
    'Lecture 14',
    'Lecture 15',
    'Lecture 16',
    'Lecture 17',
#     'Lecture 18',
#     'Lecture 19',
#     'Lecture 20',
]
# name lectures[] days[] times
instructor_list = [
    ['1', ['Lecture 1',
            'Lecture 2',
            'Lecture 3',
            'Lecture 4',
            'Lecture 5',], ['Tue', 'Wed', 'Thu'], []],
    ['2', ['Lecture 1',
            'Lecture 2',
            'Lecture 3',
            'Lecture 4',
            'Lecture 5',
            'Lecture 11',
            'Lecture 12',
            'Lecture 13',
            'Lecture 14',
            'Lecture 15',], ['Mon', 'Tue', 'Wed'], []],
    ['3', ['Lecture 6',
            'Lecture 7',
            'Lecture 8',
            'Lecture 9',
            'Lecture 10',
            'Lecture 16',
            'Lecture 17',
            'Lecture 18',
            'Lecture 19',
            'Lecture 20',], ['Thu', 'Fri'], []],
    ['4', ['Lecture 6',
            'Lecture 7',
            'Lecture 8',
            'Lecture 9',
            'Lecture 10',], [], ['10-12', '12-14']],
    ['5', ['Lecture 11',
            'Lecture 12',
            'Lecture 13',
            'Lecture 14',
            'Lecture 15',
            'Lecture 16',
            'Lecture 17',
            'Lecture 18',
            'Lecture 19',
            'Lecture 20',], [], ['8-10', '10-12']],
]
# number lectures days times
room_list = [
    [1, ['Lecture 1',
        'Lecture 2',
        'Lecture 3',
        'Lecture 4',
        'Lecture 5',
        'Lecture 6',
        'Lecture 7',
        'Lecture 8',
        'Lecture 9',
        'Lecture 10',
        'Lecture 11',
        'Lecture 12',
        'Lecture 13',
        'Lecture 14',
        'Lecture 15',
        'Lecture 16',
        'Lecture 17',
        'Lecture 18',
        'Lecture 19',
        'Lecture 20',], ['Mon'], []],
    [2, ['Lecture 1',
        'Lecture 2',
        'Lecture 3',
        'Lecture 4',
        'Lecture 5',
        'Lecture 6',
        'Lecture 7',
        'Lecture 8',
        'Lecture 9',
        'Lecture 10',], ['Mon', 'Tue', 'Wed', 'Thu'], []],
    [3, ['Lecture 11',
        'Lecture 12',
        'Lecture 13',
        'Lecture 14',
        'Lecture 15',
        'Lecture 16',
        'Lecture 17',
        'Lecture 18',
        'Lecture 19',
        'Lecture 20',], ['Tue', 'Wed', 'Thu', 'Fri'], []],
    [4, ['Lecture 1',
        'Lecture 2',
        'Lecture 3',
        'Lecture 4',
        'Lecture 5',
        'Lecture 6',
        'Lecture 7',
        'Lecture 8',
        'Lecture 9',
        'Lecture 10',], [], ['8-10']],
    [5, ['Lecture 11',
        'Lecture 12',
        'Lecture 13',
        'Lecture 14',
        'Lecture 15',
        'Lecture 16',
        'Lecture 17',
        'Lecture 18',
        'Lecture 19',
        'Lecture 20',], [], ['12-14']],
]
# day start-end
timeslot_list = [
    'Mon 8-10',
    'Mon 10-12',
    'Mon 12-14',
    'Tue 8-10',
    'Tue 10-12',
    'Tue 12-14',
    'Wed 8-10',
    'Wed 10-12',
    'Wed 12-14',
    'Thu 8-10',
    'Thu 10-12',
    'Thu 12-14',
    'Fri 8-10',
    'Fri 10-12',
    'Fri 12-14',
]

In [6]:
timetable = Timetable(lecture_list, instructor_list, room_list, timeslot_list,
                      max_lectures_per_instructor=5)

In [7]:
%%time
timetable.find_schedule()
print(timetable)

+------------+-----------+------------+------+
|  Lecture   |    Time   | Instructor | Room |
+------------+-----------+------------+------+
| Lecture 15 | Fri 10-12 |     5      | No.3 |
| Lecture 16 | Fri 12-14 |     3      | No.3 |
| Lecture 8  | Mon 10-12 |     4      | No.2 |
| Lecture 5  | Mon 10-12 |     2      | No.1 |
| Lecture 2  | Mon 12-14 |     2      | No.1 |
| Lecture 10 | Mon 12-14 |     4      | No.2 |
| Lecture 6  | Thu 10-12 |     4      | No.2 |
| Lecture 17 | Thu 10-12 |     5      | No.3 |
| Lecture 7  | Thu 12-14 |     4      | No.2 |
| Lecture 1  | Tue 10-12 |     1      | No.2 |
| Lecture 13 | Tue 10-12 |     5      | No.3 |
| Lecture 3  | Tue 12-14 |     1      | No.2 |
| Lecture 14 | Tue 12-14 |     2      | No.5 |
| Lecture 4  | Wed 10-12 |     1      | No.2 |
| Lecture 11 | Wed 10-12 |     5      | No.3 |
| Lecture 12 | Wed 12-14 |     2      | No.5 |
| Lecture 9  | Wed 12-14 |     4      | No.2 |
+------------+-----------+------------+------+
CPU times: user 7.03 s, sys: 0 ns, total: 7.03 s
Wall time: 7.04 s

Removing less constraints will probably take significantly more time.